// src/data/snippets/getting-started--frameworks/webcomponents.snippet.js
import suneditor, { plugins } from "suneditor";
import "suneditor/css/editor";
import "suneditor/css/contents";

class SunEditorElement extends HTMLElement {
  connectedCallback() {
    this.innerHTML = `<textarea></textarea>`;

    const textarea = this.querySelector("textarea");
    this.editor = suneditor.create(textarea, {
      plugins,
      value: "{{DEFAULT_VALUE}}",
      buttonList: {{BUTTON_LIST_6}}
    });
  }

  disconnectedCallback() {
    this.editor?.destroy();
  }
}

customElements.define("sun-editor", SunEditorElement);

// src/data/snippets/getting-started--frameworks/react.snippet.tsx
import { useEffect, useRef } from "react";
import suneditor, { plugins } from "suneditor";
import "suneditor/css/editor";
import "suneditor/css/contents";

export default function Editor() {
  const ref = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    const instance = suneditor.create(ref.current!, {
      plugins,
      value: "{{DEFAULT_VALUE}}",
      buttonList: {{BUTTON_LIST_6}}
    });

    return () => instance.destroy();
  }, []);

  return <textarea ref={ref} />;
}
