// src/data/snippets/getting-started--frameworks/svelte.snippet.svelte
<script>
  import { onMount } from "svelte";
  import suneditor, { plugins } from "suneditor";
  import "suneditor/css/editor";
  import "suneditor/css/contents";

  let editorEl;
  let instance;

  onMount(() => {
    instance = suneditor.create(editorEl, {
      plugins,
      value: "{{DEFAULT_VALUE}}",
      buttonList: {{BUTTON_LIST_6}}
    });

    return () => instance?.destroy();
  });
</script>

<textarea bind:this={editorEl}></textarea>

// src/data/snippets/getting-started--frameworks/vue.snippet.vue
<script setup>
import { onMounted, onBeforeUnmount, ref } from "vue";
import suneditor, { plugins } from "suneditor";
import "suneditor/css/editor";
import "suneditor/css/contents";

const editorEl = ref(null);
let instance = null;

onMounted(() => {
  instance = suneditor.create(editorEl.value, {
    plugins,
    value: "{{DEFAULT_VALUE}}",
    buttonList: {{BUTTON_LIST_4}}
  });
});

onBeforeUnmount(() => {
  instance?.destroy();
});
</script>

<template>
  <textarea ref="editorEl" />
</template>
